=== apache/tuscany-sca-cpp/sdo/runtime/core/test/bugs/1/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.mycompanyinc.com"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:mci="http://www.mycompanyinc.com" elementFormDefault="qualified"
  version="0.0.1">
  <xsd:complexType name="employeesListType">
    <xsd:sequence>
      <xsd:element name="ids" type="xsd:string" minOccurs="0"
        maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="employeeType">
    <xsd:sequence>
      <xsd:element name="id" type="xsd:string" />
      <xsd:element name="name" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="departmentType">
    <xsd:sequence>
      <xsd:element name="id" type="xsd:string" />
      <xsd:element name="name" type="xsd:string" />
      <xsd:element name="employeesList" type="mci:employeesListType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="employeesType">
    <xsd:sequence>
      <xsd:element name="employee" type="mci:employeeType" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="departmentsType">
    <xsd:sequence>
      <xsd:element name="department" type="mci:departmentType" minOccurs="0"
        maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="companyType">
    <xsd:sequence>
      <xsd:element name="employees" type="mci:employeesType" />
      <xsd:element name="departments" type="mci:departmentsType" />
    </xsd:sequence>
    <xsd:attribute name="version" type="xsd:string" use="required" />
  </xsd:complexType>
  <xsd:element name="company" type="mci:companyType" />
</xsd:schema>

=== apache/tuscany-sca-cpp/sdo/runtime/core/test/bugs/1/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<mci:company xmlns:mci="http://www.mycompanyinc.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.mycompanyinc.com company.xsd"
  version="0.0.1">
  <mci:employees>
    <mci:employee>
      <mci:id>1</mci:id>
      <mci:name>Mary Kay</mci:name>
    </mci:employee>
  </mci:employees>
  <mci:departments>
    <mci:department>
      <mci:id>3</mci:id>
      <mci:name>Sales</mci:name>
      <mci:employeesList>
        <mci:ids>1</mci:ids>
      </mci:employeesList>
    </mci:department>
  </mci:departments>
</mci:company>
