=== apache/tuscany-sca-cpp/test/ws.service.interop/resources/interop50.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *  Copyright (c) 2005-2006 The Apache Software Foundation or its licensors, as applicable.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.apache.org/tuscany/interop" 
        xmlns:tns="http://www.apache.org/tuscany/interop">   

<notation name="interop50" public="commonj.sdo"/>
                
  <element name="RootElement50">
    <complexType>
      <sequence>
        <element name="anySimpleType" type="anySimpleType" maxOccurs="unbounded"/>
        <element name="anyType" type="anyType" maxOccurs="unbounded"/>
        <element name="anyURI" type="anyURI" maxOccurs="unbounded"/>
        <element name="base64Binary" type="base64Binary" maxOccurs="unbounded"/>
        <element name="boolean" type="boolean" maxOccurs="unbounded"/>
        <element name="byte" type="byte" maxOccurs="unbounded"/>
        <element name="date" type="date" maxOccurs="unbounded"/>
        <element name="dateTime" type="dateTime" maxOccurs="unbounded"/>
        <element name="decimal" type="decimal" maxOccurs="unbounded"/>
        <element name="double" type="double" maxOccurs="unbounded"/>
        <element name="duration" type="duration" maxOccurs="unbounded"/>
        <element name="float" type="float" maxOccurs="unbounded"/>
        <element name="gDay" type="gDay" maxOccurs="unbounded"/>
        <element name="gMonth" type="gMonth" maxOccurs="unbounded"/>
        <element name="gMonthDay" type="gMonthDay" maxOccurs="unbounded"/>
        <element name="gYear" type="gYear" maxOccurs="unbounded"/>
        <element name="gYearMonth" type="gYearMonth" maxOccurs="unbounded"/>
        <element name="hexBinary" type="hexBinary" maxOccurs="unbounded"/>
        <element name="ID" type="ID" maxOccurs="unbounded"/>
        <element name="IDREF" type="IDREF" maxOccurs="unbounded"/>
        <element name="IDREFS" type="IDREFS" maxOccurs="unbounded"/>
        <element name="int" type="int" maxOccurs="unbounded"/>
        <element name="integer" type="integer" maxOccurs="unbounded"/>
        <element name="language" type="language" maxOccurs="unbounded"/>
        <element name="long" type="long" maxOccurs="unbounded"/>
        <element name="Name" type="Name" maxOccurs="unbounded"/>
        <element name="NCName" type="NCName" maxOccurs="unbounded"/>
        <element name="negativeInteger" type="negativeInteger" maxOccurs="unbounded"/>
        <element name="NMTOKEN" type="NMTOKEN" maxOccurs="unbounded"/>
        <element name="NMTOKENS" type="NMTOKENS" maxOccurs="unbounded"/>
        <element name="nonNegativeInteger" type="nonNegativeInteger" maxOccurs="unbounded"/>
        <element name="nonPositiveInteger" type="nonPositiveInteger" maxOccurs="unbounded"/>
        <element name="normalizedString" type="normalizedString" maxOccurs="unbounded"/>
        <element name="NOTATION"  maxOccurs="unbounded">
          <simpleType >
            <restriction base="NOTATION">
              <enumeration value="tns:interop50"/>
            </restriction>
          </simpleType>
        </element>
        <element name="positiveInteger" type="positiveInteger" maxOccurs="unbounded"/>
        <element name="QName" type="QName" maxOccurs="unbounded"/>
        <element name="short" type="short" maxOccurs="unbounded"/>
        <element name="string" type="string" maxOccurs="unbounded"/>
        <element name="time" type="time" maxOccurs="unbounded"/>
        <element name="token" type="token" maxOccurs="unbounded"/>
        <element name="unsignedByte" type="unsignedByte" maxOccurs="unbounded"/>
        <element name="unsignedInt" type="unsignedInt" maxOccurs="unbounded"/>
        <element name="unsignedLong" type="unsignedLong" maxOccurs="unbounded"/>
        <element name="unsignedShort" type="unsignedShort" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>
</schema>

=== apache/tuscany-sca-cpp/test/ws.service.interop/resources/interop50-in.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *  Copyright (c) 2005-2006 The Apache Software Foundation or its licensors, as applicable.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 -->
<tns:RootElement50 xmlns:tns="http://www.apache.org/tuscany/interop"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.apache.org/tuscany/interop interop50.xsd">
	<anySimpleType>anySimpleType</anySimpleType>
	<anyType>AnyTypeString</anyType>
	<anyURI>http://tempuri.org</anyURI>
	<base64Binary>ABCD</base64Binary>
	<boolean>true</boolean>
	<boolean>false</boolean>
	<boolean>1</boolean>
	<boolean>0</boolean>
	<byte>128</byte>
	<byte>-127</byte>
	<date>2001-01-01</date>
	<dateTime>2001-12-31T12:00:00</dateTime>
	<decimal>-1.23456789</decimal>
	<decimal>1.23456789</decimal>
	<double>0.0</double>
	<double>12.3E-4</double>
	<duration>P1D</duration>
	<float>0.0</float>
	<gDay>---01</gDay>
	<gMonth>--01--</gMonth>
	<gMonthDay>--01-01</gMonthDay>
	<gYear>2001</gYear>
	<gYearMonth>2001-01</gYearMonth>
	<hexBinary>0F00</hexBinary>
	<ID>idvalue0</ID>
	<IDREF>idvalue0</IDREF>
	<IDREFS>idvalue0</IDREFS>
    <int>-2147483648</int>
	<int>2147483647</int>
	<integer>-2147483648</integer>
	<integer>2147483647</integer>
	<language>EN</language>
	<long>-9223372036854775808</long>
    <long>9223372036854775807</long>
	<Name>Name</Name>
	<NCName>NCName</NCName>
	<negativeInteger>-1</negativeInteger>
	<NMTOKEN>NMTOKEN</NMTOKEN>
	<NMTOKENS>NMTOKENS</NMTOKENS>
	<nonNegativeInteger>0</nonNegativeInteger>
	<nonPositiveInteger>0</nonPositiveInteger>
	<normalizedString>normalizedString</normalizedString>
	<NOTATION>tns:interop50</NOTATION>
	<positiveInteger>1</positiveInteger>
	<QName>QName</QName>
	<short>-32768</short>
	<short>32767</short>
	<string>string</string>
	<time>12:00:00</time>
	<token>token</token>
	<unsignedByte>0</unsignedByte>
	<unsignedByte>255</unsignedByte>
	<unsignedInt>0</unsignedInt>
	<unsignedInt>4294967295</unsignedInt>
	<unsignedLong>0</unsignedLong>
	<unsignedLong>18446744073709551615</unsignedLong>	
	<unsignedShort>0</unsignedShort>
    <unsignedShort>65535</unsignedShort>
</tns:RootElement50>
